import React from 'react';

export const metadata = {
  title: "Siam | Menu",
  // description: "Generated by create next app",
};
const Menu = () => {
  return (
    <div>
      <h1>Menu</h1>
    </div>
  );
};

export default Menu;
