import "./globals.css";

import React from "react"; // Import React explicitly

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  // Determine text direction based on locale
  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale}>
      <head>
        <style>{`body { direction: ${direction}; }`}</style>
        <style>{`${inter.style}`}</style>
        <style>{`
          .ltr-component {
            direction: ltr !important; /* Force ltr direction */
            /* Add any other specific styles */
          }
        `}</style>
      </head>
      <body>
        <Header />
        <main>
          {React.Children.map(children, (child) =>
            React.isValidElement(child)
              ? React.cloneElement(child, {
                  className: `${
                    child.props.className ? child.props.className + " " : ""
                  } ltr-component`,
                })
              : child
          )}
        </main>
      </body>
    </html>
  );
}
